steps:
  #== BUILD

  # Kaniko 0.17.0 fixes chrome install bug: https://github.com/GoogleContainerTools/kaniko/issues/769
  # Kaniko 0.17.1 fixes /var/run issue in Google Cloud: https://github.com/GoogleContainerTools/kaniko/issues/1001
  # OPEN: Kaniko 0.17.x produces invalid images (whiteout?): https://github.com/GoogleContainerTools/kaniko/issues/1039
  # CLOSED?: New Kaniko version SHOULD fix this, pinning tot he debug tag mentioned here: https://github.com/GoogleContainerTools/kaniko/issues/1039#issuecomment-590954787
  - name: 'gcr.io/kaniko-project/executor:a1af057f997316bfb1c4d2d82719d78481a02a79'
    id: Build Container
    args:
      - --destination=gcr.io/$PROJECT_ID/refsheet-admin-frontend-ci:$REVISION_ID
      - --cache=true
      - --dockerfile=./Dockerfile.ci

  - name: 'gcr.io/$PROJECT_ID/refsheet-admin-frontend-ci:$REVISION_ID'
    id: Prettier Check
    dir: /app
    env:
      - CI=true
    args: ['npm', 'run', 'prettier-check']
    waitFor:
      - Build Container

  - name: 'gcr.io/$PROJECT_ID/refsheet-admin-frontend-ci:$REVISION_ID'
    id: ESLint
    dir: /app
    env:
      - CI=true
    args: ['npm', 'run', 'eslint']
    waitFor:
      - Build Container

  - name: 'gcr.io/$PROJECT_ID/refsheet-admin-frontend-ci:$REVISION_ID'
    id: Jest
    dir: /app
    env:
      - CI=true
    args: ['npm', 'run', 'test']
    waitFor:
      - Build Container
